// OpenNext generates this module during build; it is absent in a fresh checkout.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext.
import handler from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  async scheduled(_event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    if (!env.CRON_SECRET) throw new Error("Publisher cron secret is not configured");
    // Invoke Next inside its normal request context so D1 bindings and cache
    // invalidation work. No public HTTP round trip or external scheduler needed.
    const response = await handler.fetch(new Request("https://zibukecommunity.co.za/api/cron/publisher", {
      method: "POST", headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    }), env, ctx);
    if (!response.ok) throw new Error(`Publisher failed (${response.status})`);
    await response.body?.cancel();
  },
} satisfies ExportedHandler<CloudflareEnv>;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
