// OpenNext generates this module during build; it is absent in a fresh checkout.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext.
import handler from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  async scheduled(event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    if (!env.CRON_SECRET) throw new Error("Cron secret is not configured");
    const route = event.cron === "0 * * * *" ? "publisher" : event.cron === "*/15 * * * *" ? "billing" : null;
    if (!route) throw new Error("Unknown cron schedule");
    // Invoke Next inside its normal request context so D1 bindings and cache
    // invalidation work. No public HTTP round trip or external scheduler needed.
    const task = (async () => {
      const response = await handler.fetch(new Request(`https://zibukecommunity.co.za/api/cron/${route}`, {
        method: "POST", headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      }), env, ctx);
      const diagnostics = await response.text();
      console.log("Scheduled publisher/billing result", { route, status: response.status, diagnostics });
      if (!response.ok) throw new Error(`${route} failed (${response.status}): ${diagnostics}`);
    })();
    ctx.waitUntil(task);
    await task;
  },
} satisfies ExportedHandler<CloudflareEnv>;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by OpenNext.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
